name: flutter_custom_caraousel_v2
description: "A customizable carousel for Flutter with Material Design 3 support, multiple layouts and indicator styles."
version: 0.1.0
homepage: https://pub.dev/packages/flutter_custom_caraousel_v2
repository: https://github.com/adampermana/flutter_custom_caraousel_v2
issue_tracker: https://github.com/adampermana/flutter_custom_caraousel_v2/issues
topics: [caraousel, flutter-custom-caraousel-v2, flutter-caraousel, caraousel-slider, custom-caraousel]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0